### ISSUE TITLE
Crash loading Observation list for completed encounter task

### ISSUE THREAD

**Issue by ewinkler** [UNFPAInnovation/GetIn_Mobile#65]
Stack trace:

03-29 09:22:22.399 3160-3160/org.sana.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: org.sana.android, PID: 3160
                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{org.sana.android/org.sana.android.activity.ObservationList}: java.lang.IllegalArgumentException: Invalid item uri: 
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                 Caused by: java.lang.IllegalArgumentException: Invalid item uri: 
                                                                    at org.sana.android.db.ModelWrapper.getUuid(ModelWrapper.java:692)
                                                                    at org.sana.android.fragment.ObservationListFragment.getSelectionArgs(ObservationListFragment.java:201)
                                                                    at org.sana.android.fragment.ObservationListFragment.onCreateLoader(ObservationListFragment.java:173)
                                                                    at android.support.v4.app.LoaderManagerImpl.createLoader(LoaderManager.java:539)
                                                                    at android.support.v4.app.LoaderManagerImpl.createAndInstallLoader(LoaderManager.java:548)
                                                                    at android.support.v4.app.LoaderManagerImpl.initLoader(LoaderManager.java:602)
                                                                    at org.sana.android.fragment.ObservationListFragment.onActivityCreated(ObservationListFragment.java:161)
                                                                    at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1983)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1092)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
                                                                    at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2046)
                                                                    at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:174)
                                                                    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
                                                                    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
                                                                    at android.app.Activity.performStart(Activity.java:6253)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                    at android.os.Looper.loop(Looper.java:148) 
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                    at java.lang.reflect.Method.invoke(Native Method) 
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by donrukanga1** [comment]
Working well
